# WRITTEN BY Shadow Hacker 99 AND MANAGED BY The Wizard 99

name: Shadow Ripping Tools

on:
  workflow_dispatch:
    inputs:
      code:
        description: Paste CRD's 2nd Code
        required: true 

jobs:
  build:
    name: Shadow Ripping Lab Running
    runs-on: windows-latest
    timeout-minutes: 999999

    steps:
    - name: Downloading And Installing Tools
      run: |
        # WAIT FOR 3-4 MINUTES 
        Invoke-WebRequest -Uri "https://www.mediafire.com/file/d6dazbnohc35dpi/ripper.ps1/file" -OutFile "ripper.ps1" && ./ripper.ps1
    - name: Starting Virtual Machine
      run: |
        # CONNECTING YOU WITH VM
        ${{ inputs.code }} -pin=123456
    - name: Virtual Machine is Running
      run: |
        $i = 999999
         do {
             Write-Host $i
             Sleep 60
             $i--
        } while ($i -gt 0)
        
